name: format translations
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'src/resources/resources/assets/waila/lang/**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "git_hash=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.repository != 'badasintended/wthit' }}
      - run: ./gradlew formatTranslation --max-workers=1
        env:
          GIT_HASH: ${{ steps.vars.outputs.git_hash }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: format translations
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
